# .github/workflows/release.yml
name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write  # for trusted publishing (preferred)
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist/wheel
        run: python -m build

      - name: Check artifacts
        run: python -m twine check dist/*

      # Option A: Trusted Publishing (enable in PyPI project first)
      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     skip-existing: true

      # Option B: Token-based (if not using trusted publishing)
      - name: Publish to PyPI (token)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true